name: CI/CD

on:
  push:
    branches:
      - '**'        # trigger for all branches
  pull_request:
    branches:
      - main       # Trigger on PR creations

jobs:
  # --------- Feature / other branches ---------
  build-test:
    if: github.ref != 'refs/heads/main' || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Run unit tests
        run: dotnet test --no-build --verbosity normal

  # --------- Main branch merge ---------
  release:
    if: github.ref == 'main'
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: actions/checkout@v4

      # GitVersion setup
      - name: Install GitVersion
        uses: GitTools/actions/gitversion/setup@v0.9.14

      - name: Calculate version
        id: gitversion
        uses: GitTools/actions/gitversion/execute@v0.9.14
        with:
          useConfigFile: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Pack
        run: |
          echo "GitVersion.FullSemVer=${{ steps.gitversion.outputs.FullSemVer }}"
          dotnet pack -c Release -p:PackageVersion=${{ steps.gitversion.outputs.NuGetVersionV2 }} -o ./artifacts

      - name: List artifacts
        run: ls -la ./artifacts

      - name: Publish
        run: dotnet nuget push ./artifacts/*.nupkg \
              --source "github" \
              --api-key ${{ secrets.GH_PACKAGES_TOKEN }}
